name: CI

# Trigger the workflow on push or pull request, but only for the main branch
on:
  pull_request:
  push:
    branches: ["main"]

jobs:
  generateMatrix:
    name: "Generate matrix from cabal"
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Checkout base repo
        uses: actions/checkout@v2
      - name: Extract the tested GHC versions
        id: set-matrix
        run: |
          wget https://github.com/Kleidukos/get-tested/releases/download/v0.1.5.0/get-tested-0.1.5.0-linux-amd64 -O get-tested
          chmod +x get-tested
          ./get-tested --ubuntu --macos servant-effectful.cabal >> $GITHUB_OUTPUT
  tests:
    name: ${{ matrix.ghc }} on ${{ matrix.os }}
    needs: generateMatrix
    runs-on: ${{ matrix.os }}
    strategy:
      matrix: ${{ fromJSON(needs.generateMatrix.outputs.matrix) }}
    steps:
    - uses: actions/checkout@v4

    - name: Set up Haskell
      id: setup-haskell
      uses: haskell-actions/setup@v2
      with:
        ghc-version: "${{ matrix.ghc }}"
        cabal-version: "latest"
    - name: Cache
      uses: actions/cache@v3.3.2
      with:
        path: ${{ steps.setup-haskell.outputs.cabal-store }}
        key: ${{ runner.os }}-ghc-${{ matrix.ghc }}-cabal-${{ hashFiles('**/plan.json') }}
        restore-keys: ${{ runner.os }}-ghc-${{ matrix.ghc }}-

    - name: Build
      run: cabal build -j
